const myLabPayloads = [
    "GET / HTTP/1.1\r\n",
    "GET / HTTP/1.1\r\nHost: example.com\r\n",
    "GET / HTTP/1.1\r\nHost: example.com\r\nX-Forwarded-For: 127.0.0.1\r\nX-Forwarded-For: 192.168.0.1\r\n",
    "GET /?id=1'; DROP TABLE users; -- HTTP/1.1\r\nHost: example.com\r\n",
    "GET / HTTP/1.1\r\nHost: example.com\r\nX-Foo-ä: bar\r\n",
    "GET /path/to/resource/too/long HTTP/1.1\r\nHost: example.com\r\n",
    "GIBBERISH / HTTP/1.1\r\nHost: example.com\r\n",
    "GET / HTTP/2.0\r\nHost: example.com\r\n",
    "\\x47\\x45\\x54 / HTTP/1.1\r\nHost: example.com\r\n",
    "GET / HTTP/1.1\r\nHost: example.com\r\nX-Foo: <large_value>\r\n",
    "POST / HTTP/1.1\r\nHost: example.com\r\nContent-Length: 100\r\nContent-Length: 200\r\n",
    "POST / HTTP/1.1\r\nHost: example.com\r\nContent-Length: abc\r\n",
    "GET / HTTP/1.1\r\nHost: example.com\r\nX-Evil-Header: <malicious_script>\r\n",
    "GET / HTTP/1.1\r\nHost: example.com\r\nX-Foo: \\x00\\x01\\x02\r\n",
    "/ HTTP/1.1\r\nHost: example.com\r\n",
    "GET /../../../../etc/passwd HTTP/1.1\r\nHost: example.com\r\n",
    "GET /%zz% HTTP/1.1\r\nHost: example.com\r\n",
    "GET /path/with/<> HTTP/1.1\r\nHost: example.com\r\n"
